2. Read in dataset

In [1]:
import pandas as pd

In [2]:
delaney_with_descriptors_url = 'https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv'
dataset = pd.read_csv(delaney_with_descriptors_url)

In [3]:
dataset

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
0     2.59540  167.850                0.0            0.000000 -2.180
1     2.37650  133.405                0.0            0.000000 -2.000
2     2.59380  167.850                1.0            0.000000 -1.740
3     2.02890  133.405                1.0            0.000000 -1.480
4     2.91890  187.375                1.0            0.000000 -3.040
...       ...      ...                ...                 ...    ...
1139  1.98820  287.343                8.0            0.000000  1.144
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893
1142  2.56214  354.815                3.0            0.521739 -3.790
1143  2.02164  179.219                1.0            0.461538 -2.581

[1144 rows x 5 columns]

In [ ]:
3. Model Building
3.1. Model Setup

In [6]:
from pycaret.regression import *

In [7]:
model = setup(data = dataset, target = 'logS', train_size=0.8, silent=True)

In [8]:
compare_models()

3.3. Model Creation

In [9]:
et = create_model('et')

3.4. Model Tuning
The learning parameters are subjected to optimization at this phase. Here, 50 iterations is used for the optimization process and the fitness function is the Mean Absolute Error (MAE) which is the performance metric used to judge at which learning parameter settings are optimal.

In [10]:
tuned_et = tune_model('et', n_iter = 50, optimize = 'mae')

TypeError: The behavior of tune_model in version 1.0.1 is changed. Please pass trained model object.

In [ ]:
print(tuned_et)

4. Model Analysis
4.1. Plot Models
In this tutorial, we are performing regression and so further details of the regression plots are available at https://pycaret.org/plot-model/.

In [ ]:
Residuals Plot

In [ ]:
plot_model(et, 'residuals')

In [ ]:
Prediction Error Plot

In [ ]:
plot_model(et, 'error')

In [ ]:
Cooks Distance Plot

In [ ]:
plot_model(et, 'cooks')

In [ ]:
Recursive Feature Selection

In [ ]:
plot_model(et, 'rfe')

In [ ]:
Learning Curve

In [ ]:
plot_model(et, 'learning')

In [ ]:
Validation Curve

In [ ]:
plot_model(et, 'vc')

In [ ]:
Manifold Learning

In [ ]:
plot_model(et, 'manifold')

In [ ]:
Feature Importance

In [ ]:
plot_model(et, 'feature')

In [ ]:
Model Hyperparameter

In [ ]:
The hyperparameter of the learning model is displayed using the parameter argument in inside the plot_model() function.

In [ ]:
plot_model(tuned_et, 'parameter')

In [ ]:
The evaluate_model() displays all available plots here.

In [ ]:
evaluate_model(tuned_et)
interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [ ]:
4.2. Model Interpretaion
The interpret_model() function of PyCaret leverages the use of the SHAP library to produce stunning plots for depicting the SHAP (SHapley Additive exPlanations) values that was originally proposed by Lundberg and Lee in 2016.$^5$ In a nutshell, SHAP plots adds interpretability to constructed models so that the contribution of each features to the prediction can be elucidated.

Summary Plot

In [ ]:
interpret_model(et)

In [ ]:
Correlation Plot

In [ ]:
interpret_model(et, plot = 'correlation')

In [ ]:
Reason Plot at Observation Level

The Reason Plot at Observation Level as called by PyCaret is better known as the force plot and this plot essentially describes the push and pull effect that each individual features has on the base value that eventually leads to the predicted output value.

In [ ]:
In [ ]:
interpret_model(et, plot = 'reason', observation = 10)

In [ ]:
Out[ ]:
Visualization omitted, Javascript library not loaded!

In [ ]:
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.

In [ ]:
6.6. External Testing
We will now apply the trained model (built with 80% subset) to evaluate on the so-called "hold-out" testing set (the 20% subset) that serves as the unseen data.

In [ ]:
prediction_holdout = predict_model(et)

In [ ]:
prediction_holdout.head()